### ISSUE TITLE
Config file with only exclude rules do not work as expected

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/cloud-nuke#198]
I don't remember if this was intentional or not.

If you create a config file where there is only an exclude rule, intuitively this should mean "include everything but what is requested to be excluded," but in practice this becomes "exclude everything" because `cloud-nuke` treats empty `include` rules as "include nothing."

You can work around this by adding an explicit `include` rule to include everything:

```yaml
s3:
  include:
    names_regex:
      - ".*"
  exclude:
    names_regex:
      - "^my-real-s3-bucket$"
```
