### ISSUE TITLE
Exclusion support for SNS Topics?

### ISSUE THREAD

**Issue by chrisswanda** [gruntwork-io/cloud-nuke#359]
I created an config/exclusion file to for SNS Topics, so that I can keep certain SNS topics during a nuke session of my sandbox account.

```
SNSTopic:
  include:
  exclude:
    names_regex:
      - Sandbox
```

When I run `cloud-nuke aws --resource-type snstopic --region us-east-2 --config sandbox_exclusion.yml --dry-run` it still identifies SNS topics that are to be nuked.  Are SNS topics supported for config files?

I'm on `cloud-nuke version v0.19.0`
