### ISSUE TITLE
In config how to exclude some resource only on specific region?

### ISSUE THREAD

**Issue by mgzenitech** [gruntwork-io/cloud-nuke#462]
Hypothetical config:

```yaml
DynamoDB:
  exclude:
    names_regex:
      - TF-Locks
    region: ????
```
