### ISSUE TITLE
KMSCustomerKeys regex filter not working as expected

### ISSUE THREAD

**Issue by stefan-nordcloud** [gruntwork-io/cloud-nuke#791]
I have a config file with the following snippet in it:
```
 KMSCustomerKeys:
   exclude:
     names_regex:
       - ^prov-.*
```
However, when I run cloud-nuke it still includes a KMS key with the alias `prov-pv-shared-ebs`. If I change the regex to the following, the filter correctly excludes my KMS key.
```
 KMSCustomerKeys:
   exclude:
     names_regex:
       - prov-.*
```
I'd have expected both regex to exclude the key with the above alias. Am I doing something wrong or can you reproduce the same behavior?

**Comment by wakeful** [comment]
hey @stefan-nordcloud,

what version of `cloud-nuke` are you using? is it the latest `master` or something older?

**Comment by wakeful** [comment]
I did a quick look using latest master branch - AWS API is returning the name with prefix `alias/my_new_key` 

could you try this?

```yaml
 KMSCustomerKeys:
   exclude:
     names_regex:
       - ^alias/prov-.*
 ```
