### ISSUE TITLE
Question regarding the force flag and the cloud-nuke-excluded tag

### ISSUE THREAD

**Issue by ErezWeiss** [gruntwork-io/cloud-nuke#812]
In my cloud I have a VPC, subnet and an EC2.

I tried to run cloud Nuke:
```
          ./cloud-nuke_linux_amd64 aws \
            --older-than 1m \
            --region us-east-1 \
            --delete-unaliased-kms-keys \
            --exclude-resource-type vpc \
            --exclude-resource-type ec2_dhcp_option \
            --exclude-resource-type kmscustomerkeys \
            --exclude-resource-type app-runner-service \
            --exclude-resource-type managed-prometheus \
            --config config/config.yaml \
            --force
```

I wanted to exclude a specific EC2 and a specific subnet, tagged with `cloud-nuke-excluded: true`
![image](https://github.com/user-attachments/assets/f59ec734-7b73-4bce-8d41-33530e6e4eb1)

this is the scan result: 
![image](https://github.com/user-attachments/assets/2241b22a-d7a1-427c-892e-2d7d56fdee4e)

BUT THE EC2 WAS DELETED!
I don't get the rules here, if someone can explain me

edit: my config file is: 

```
OIDCProvider:
  exclude:
    names_regex:
      - AWSSSO*
      - token.actions.githubusercontent.com
  protect_until_expire: true

CloudtrailTrail:
  exclude:
      names_regex:
          - controltower*
  protect_until_expire: true

LambdaFunction:
  exclude:
    names_regex:
      - controltower*
  protect_until_expire: true

CloudWatchLogGroup:
  exclude:
    names_regex:
      - controltower*
  protect_until_expire: true

ConfigServiceRecorder:
  exclude:
    names_regex:
      - controltower*
  protect_until_expire: true

ECRRepository:
  exclude:
    names_regex:
      - cdk*
  protect_until_expire: true

DynamoDB:
  exclude:
    names_regex:
      - terraform*
  protect_until_expire: true

s3:
  exclude:
    names_regex:
      - cdk*
      - terraform*
  protect_until_expire: true

IAMRoles:
  exclude:
    names_regex:
      - ControlTower*
      - controltower*
      - cdk*
      - ExecutionRole*
      - ServiceRole*
      - stacksets*
      - admin*
  protect_until_expire: true

IAMServiceLinkedRoles:
  exclude:
    names_regex:
      - ControlTower*
      - ServiceRole*
  protect_until_expire: true

SNS:
  exclude:
    names_regex:
      - controltower*
  protect_until_expire: true
```
