### ISSUE TITLE
exclusion not working as intended

### ISSUE THREAD

**Issue by oleviacode** [gruntwork-io/cloud-nuke#835]
I want to exclude deleting EC2 instances and used the example from examples/complete.yaml

heres my config.yaml:

```
EC2:
  exclude:
    names_regex:
      - this.*
    tag: 'test'
    tag_value: 'test'
```

I've created an EC2 instances named "thisIsATest" in  ap-southeast-1, and once its fully running. I tested to see if the EC2 will be excluded by running 

`cloud-nuke aws --region ap-southeast-1 --resource-type ec2 --dry-run`

I expect it to not include the above EC2 but yet it is included. Please let me know if I'm doing anything wrong, thank you!/
