### ISSUE TITLE
Request: Inclusion tags, inclusion based on absence of tags

### ISSUE THREAD

**Issue by Gxrjan** [gruntwork-io/cloud-nuke#876]
# Inclusion tags

It would be beneficial to include resources based on tags. If it is supported for names of resources, how come it's not supported for tags?
Example:
```
SecurityGroup:
  include:
    tags:
      Team: "CloudTeam"
```
Only security groups with the `Team=CloudTeam` tag will be considered for nuking.

Speaking of this topic, the config complete [example](https://github.com/gruntwork-io/cloud-nuke/blob/master/config/examples/complete.yaml) specifies tag as a possible value for inclusion, but from what I could tell, it's not implemented. 

# Inclusion based on the absence of tags

If the inclusion based on tags is implemented, it would be also nice to include resource based absence of certain tags. Example:
```
SecurityGroup:
  include:
    tags:
      Team: null
```
This will include all security groups that are not tagged with the `Team` tag. 

I'm trying to use cloud-nuke as a kind of tagging enforcement strategy. My policy is: if something is not properly tagged, it will be destroyed. But in the current implementation, it's not possible. Exclusion tags are evaluated as OR statement, so I can't check all required tags. If filtering based on the absence of tags is implemented I would be able to write the following:
```
SecurityGroup:
  include:
    tags:
      Team: null
      Service: null
```
All security groups that don't have either `Team` or `Service` tag will be included.

**Comment by james03160927** [comment]
Hi @Gxrjan, thanks for creating the issue — I appreciate you getting that started.

I'll explore how we can expand the tagging capability to include resources as well. I'll do some prototyping and get back to you with an update soon.

**Comment by james03160927** [comment]
With exclusion tags, the logic is OR-based - if ANY exclusion rule matches, the resource is excluded. For your use case, you'd theoretically try something like:

```
SecurityGroup:
  exclude:
    tags:
      Team: ".*"     # exclude if Team tag exists
      Service: ".*"  # exclude if Service tag exists
```

But this would exclude resources that have EITHER Team OR Service tags. What you actually want is to exclude only resources that have BOTH Team AND Service tags (i.e., only include resources missing at least one required tag).

-----

Updated the code to support what you are planning to achieve.
